import { Token, OptimizedOp, Instruction, Program } from './types';

/**
 * Compile a brainfuck program into executable JavaScript source code.
 * The generated code uses a Uint8Array for memory and readline for input.
 */
export function compile(program: Program): string {
  const lines: string[] = [];

  lines.push('#!/usr/bin/env node');
  lines.push('// Generated by brainfuck-ts compiler');
  lines.push('// https://github.com/brainfuck-ts');
  lines.push('');
  lines.push("'use strict';");
  lines.push('');
  lines.push('const memory = new Uint8Array(30000);');
  lines.push('let ptr = 0;');
  lines.push('let output = "";');
  lines.push('');
  lines.push('// Input handling');
  lines.push('const inputStr = process.argv[2] || "";');
  lines.push('const inputBytes = Array.from(inputStr).map(c => c.charCodeAt(0));');
  lines.push('let inputIdx = 0;');
  lines.push('');
  lines.push('function readByte() {');
  lines.push('  if (inputIdx < inputBytes.length) return inputBytes[inputIdx++];');
  lines.push('  return 0;');
  lines.push('}');
  lines.push('');
  lines.push('// Program');
  lines.push('(function main() {');

  compileBlock(program, lines, 1);

  lines.push('})();');
  lines.push('');
  lines.push('process.stdout.write(output);');
  lines.push('');

  return lines.join('\n');
}

function indent(depth: number): string {
  return '  '.repeat(depth);
}

function compileBlock(instructions: Program, lines: string[], depth: number): void {
  for (const instr of instructions) {
    compileInstruction(instr, lines, depth);
  }
}

function compileInstruction(
  instr: Instruction,
  lines: string[],
  depth: number
): void {
  const pad = indent(depth);

  switch (instr.op) {
    case Token.Plus:
      if (instr.count === 1) {
        lines.push(`${pad}memory[ptr] = (memory[ptr] + 1) & 0xFF;`);
      } else if (instr.count === -1) {
        lines.push(`${pad}memory[ptr] = (memory[ptr] - 1) & 0xFF;`);
      } else if (instr.count > 0) {
        lines.push(`${pad}memory[ptr] = (memory[ptr] + ${instr.count}) & 0xFF;`);
      } else {
        lines.push(`${pad}memory[ptr] = (memory[ptr] - ${-instr.count}) & 0xFF;`);
      }
      break;

    case Token.Right:
      if (instr.count === 1) {
        lines.push(`${pad}ptr++;`);
      } else if (instr.count === -1) {
        lines.push(`${pad}ptr--;`);
      } else if (instr.count > 0) {
        lines.push(`${pad}ptr += ${instr.count};`);
      } else {
        lines.push(`${pad}ptr -= ${-instr.count};`);
      }
      break;

    case Token.Read:
      lines.push(`${pad}memory[ptr] = readByte();`);
      break;

    case Token.Write:
      lines.push(`${pad}output += String.fromCharCode(memory[ptr]);`);
      break;

    case Token.Open:
      lines.push(`${pad}while (memory[ptr] !== 0) {`);
      compileBlock(instr.innerOps!, lines, depth + 1);
      lines.push(`${pad}}`);
      break;

    case OptimizedOp.Clear:
      lines.push(`${pad}memory[ptr] = 0;`);
      break;

    case OptimizedOp.ScanRight:
      lines.push(`${pad}while (memory[ptr] !== 0) ptr++;`);
      break;

    case OptimizedOp.ScanLeft:
      lines.push(`${pad}while (memory[ptr] !== 0) ptr--;`);
      break;

    case OptimizedOp.Copy:
      lines.push(`${pad}if (memory[ptr] !== 0) {`);
      lines.push(`${pad}  memory[ptr + ${instr.offset}] = (memory[ptr + ${instr.offset}] + memory[ptr]) & 0xFF;`);
      lines.push(`${pad}  memory[ptr] = 0;`);
      lines.push(`${pad}}`);
      break;

    case OptimizedOp.Multiply:
      lines.push(`${pad}if (memory[ptr] !== 0) {`);
      lines.push(`${pad}  memory[ptr + ${instr.offset}] = (memory[ptr + ${instr.offset}] + memory[ptr] * ${instr.multiplier}) & 0xFF;`);
      lines.push(`${pad}  memory[ptr] = 0;`);
      lines.push(`${pad}}`);
      break;
  }
}
